xbox_teleop:
  ros__parameters:
    axis_linear_x: 1      # Stick izquierdo arriba/abajo (adelante/atrás)
    axis_linear_y: 0      # Stick izquierdo izq/der (strafe lateral)
    axis_angular_yaw: 2   # Stick derecho izq/der (giro)
    enable_button: 7      # Botón RB de seguridad
    scale_linear_x: 1.0
    scale_linear_y: 1.0
    scale_angular_yaw: 1.0
    cmd_vel_topic: /roborescue/cmd_vel
